addons:
  sauce_connect:
#  username: xupyprmv
#  access_key: f19d1c49-74e5-4e7a-b340-70bac7948b1a
#    username: semantic-machines
#    access_key: 92a54db7-283e-4b3d-96ab-b2df3f6e02ff
  username: itiu
  access_key: 2762d6d6-6f43-4166-982d-db5ce578f53b

env:
  global:
    - secure: PYwCZBpLe87Qg2RXibiGk9LrNrkFMlGuFnf/mp+f5kc4bFoVMo7Pl+Rdl4S1H33kLYK6d3pFggddwWxO7HGH9IyHzQ6Gfu3u9gR9rJXovQYfEp8muDCJDXvLEUoMxRgnRPa202p+BUnrNMwebxYHmwgef0s1dYQpRsewmPWHevk=
    - secure: s1BV5JjhQIIdasowuMW2OqH5LjvN3tnU+sEGdz4HxWpHufgFUeNBVzu13S85qSxdch55lCyB4ft58PAX3q0wHFPYvBEwkvMlSFny7LeiytW9HZ/fkCG+Dwh6H6OEK1jKQriXZrYLQm4m6gnnAQYsUpDhxP12YejyyBbfaVW73Og=

language: d
d: dmd-2.068.2

# Load all dependencies
# Compile vibe-d before main project to prevent OutOfMemory issue
before_install:
  - sudo apt-get update
  - ./control-install.sh    
  - dub -v fetch vibe-d
  - npm install selenium-webdriver

# Build
install:
  - dub build --build=debug

# Run service as daemon and GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - start-stop-daemon --start --verbose --chdir $PWD --make-pidfile --pidfile $PWD/veda-pid --background --startas /bin/bash -- -c "exec ./veda >> $PWD/veda.log 2>&1"
  - sleep 60  # give Web server some time to bind to sockets, load startup data, etc

# Run API & integration test
script:
  - node ./qa/testAPI.js
  - node ./qa/testLogin.js
  - node ./qa/testPerson.js

# Stop deamon and show log
after_script:
  - start-stop-daemon -Kp $PWD/veda-pid $PWD/veda
  - cat $PWD/veda.log