addons:
  sauce_connect:
    username: semanticmachines
    access_key: 0fdd3d85-3d51-4fd5-89ed-10980baa57a5

env:
  global:
    - secure: PYwCZBpLe87Qg2RXibiGk9LrNrkFMlGuFnf/mp+f5kc4bFoVMo7Pl+Rdl4S1H33kLYK6d3pFggddwWxO7HGH9IyHzQ6Gfu3u9gR9rJXovQYfEp8muDCJDXvLEUoMxRgnRPa202p+BUnrNMwebxYHmwgef0s1dYQpRsewmPWHevk=
    - secure: s1BV5JjhQIIdasowuMW2OqH5LjvN3tnU+sEGdz4HxWpHufgFUeNBVzu13S85qSxdch55lCyB4ft58PAX3q0wHFPYvBEwkvMlSFny7LeiytW9HZ/fkCG+Dwh6H6OEK1jKQriXZrYLQm4m6gnnAQYsUpDhxP12YejyyBbfaVW73Og=

language: d
d: dmd-2.070.0

# Load all dependencies
# Compile vibe-d before main project to prevent OutOfMemory issue
before_install:
  - sudo apt-get update
  - ./control-install.sh    
  - dub -v fetch vibe-d
  - npm install selenium-webdriver@2.47.0
  - npm install -g grunt-cli
  - npm install grunt-contrib-qunit --save-dev
  - npm install coveralls --save-dev
  - npm install grunt-coveralls --save-dev

# Build
install:
  - ./build.sh

# Run service as daemon and GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - start-stop-daemon --start --verbose --chdir $PWD --make-pidfile --pidfile $PWD/veda-pid --background --startas /bin/bash -- -c "exec ./veda >> $PWD/veda.log 2>&1"
  - sleep 90  # give Web server some time to bind to sockets, load startup data, etc

# Run API & integration test
script:
  - grunt test
  - cat $PWD/*.log          
  - grunt coveralls
#  - node ./qa/testAPI.js
  - node ./qa/testLogin.js
  - node ./qa/testPerson.js
  - node ./qa/testJournal.js

# Stop deamon and show log
after_script:
  - start-stop-daemon -Kp $PWD/veda-pid $PWD/veda
  - grunt coveralls
  - cat $PWD/*.log          
