sudo: required
dist: trusty

addons:
  sauce_connect:
    username: semanticmachines
    access_key: 0fdd3d85-3d51-4fd5-89ed-10980baa57a5
    no_ssl_bump_domains: localhost

language: 
    - rust
    - go

go:  1.8

env:
  global:
    - secure: PYwCZBpLe87Qg2RXibiGk9LrNrkFMlGuFnf/mp+f5kc4bFoVMo7Pl+Rdl4S1H33kLYK6d3pFggddwWxO7HGH9IyHzQ6Gfu3u9gR9rJXovQYfEp8muDCJDXvLEUoMxRgnRPa202p+BUnrNMwebxYHmwgef0s1dYQpRsewmPWHevk=
    - secure: s1BV5JjhQIIdasowuMW2OqH5LjvN3tnU+sEGdz4HxWpHufgFUeNBVzu13S85qSxdch55lCyB4ft58PAX3q0wHFPYvBEwkvMlSFny7LeiytW9HZ/fkCG+Dwh6H6OEK1jKQriXZrYLQm4m6gnnAQYsUpDhxP12YejyyBbfaVW73Og=
    - secure: C4QaKE9icNEBbfPGqusjV+koFOa+Ggj3FtwoopB6WinN3ralCEhPJlcSEPSNSNRyS8fJqLq9J/9YQjLYTxhEal8usfeIe/WUrBXYW1/rSzoP6RSnLHrD99NYWO8aHpXxlhxU5T3QSFHq/wvDLBuhw1hlu0osNH9b1S29dPE8P4w=

# Load all dependencies
before_install:
  - ./control-install.sh&>install.log    
#  - cat install.log
  - npm install selenium-webdriver@2.47.0
  - npm install -g grunt-cli
  - npm install grunt-contrib-qunit --save-dev
  - npm install grunt --save-dev
  - npm install coveralls --save-dev
  - npm install grunt-coveralls --save-dev
  - go version    

# Build
install:
  - ./build.sh

# Run service as daemon and GUI
before_script:
  - tarantool --version    
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
#  - start-stop-daemon --start --verbose --chdir $PWD --make-pidfile --pidfile $PWD/veda-pid --background --startas /bin/bash -- -c "exec ./veda >> $PWD/veda_s.log 2>&1"
  - ./control-start.sh
  - sleep 120  # give Web server some time to bind to sockets, load startup data, etc
  - ls  $PWD   
  - ls  $PWD/logs   
  - cat $PWD/logs/tarantool-stdout.log
  - cat $PWD/logs/tarantool-stderr.log
  - ls  $PWD/data/tarantool
  - cat $PWD/data/tarantool/tarantool.log
#  - cat $PWD/logs/veda-fanout-email-stderr.log
#  - cat $PWD/logs/veda-fanout-sql-stderr.log
  - cat $PWD/logs/veda-ft-indexer-stderr.log
  - cat $PWD/logs/veda-ltr-scripts-stderr.log
  - cat $PWD/logs/veda-scripts-lp-stderr.log
  - cat $PWD/logs/veda-scripts-main-stderr.log
#  - cat $PWD/logs/veda-core-scripts-main*.log
  - cat $PWD/logs/veda-server-stderr.log
#  - cat $PWD/logs/veda-ttlreader-stderr.log
  - cat $PWD/logs/veda-gowebserver-stderr.log 
#  - cat $PWD/veda_s.log
  - cat $PWD/logs/veda-core-server_*.log          
  - ps aux | grep veda

# Run API & integration test
script:
  - grunt test --stack --verbose
#  - grunt coveralls
#  - node ./qa/testAPI.js
#  - node ./qa/testLogin.js
#  - node ./qa/testPerson.js
#  - node ./qa/testDrafts.js
#  - node ./qa/testDeleteAndRecovery.js
#  - node ./qa/testRights.js
#  - node ./qa/testComment.js
#  - node ./qa/testVersionedDocument.js
#  - node ./qa/testJournal.js
#  - node ./qa/testAttachment.js
#  - node ./qa/testPager.js
#  - node ./qa/testSearchRangeOfDates.js
#  - node ./qa/testAttributiveSearchPerson.js
#  - node ./qa/testCreatingNetInterface.js
#  - node ./qa/testRepeatComplexRoute.js
#  - node ./qa/testNetComplexRoute.js
#  - node ./qa/testSimpleNet.js
#  - node ./qa/testSimpleNet2.js
#  - node ./qa/testSimpleNet3.js
#  - node ./qa/testSimpleWorkflow.js
#  - node ./qa/testDelegationDocument.js
#  - node ./qa/testLanguage.js

# Stop deamon and show log
after_script:
  - start-stop-daemon -Kp $PWD/veda-pid $PWD/veda
  - grunt coveralls
  - date    
  - cat $PWD/veda_s.log
  - cat $PWD/logs/tarantool-stdout.log
  - cat $PWD/logs/tarantool-stderr.log
  - ls  $PWD/data/tarantool
  - cat $PWD/data/tarantool/tarantool.log
  - cat $PWD/logs/veda-core-_*.log 
  - cat $PWD/logs/veda-core-fanout_*.log
  - cat $PWD/logs/veda-core-fulltext_indexer_*.log
  - cat $PWD/logs/veda-core-scripts-main*.log
  - cat $PWD/logs/veda-core-server_*.log
#  - cat $PWD/logs/veda-core-ttl_reader_*.log
#  - cat $PWD/logs/veda-fanout-email-stderr.log
  - cat $PWD/logs/veda-fanout-sql-stderr.log
  - cat $PWD/logs/veda-ft-indexer-stderr.log
  - cat $PWD/logs/veda-ltr-scripts-stderr.log
  - cat $PWD/logs/veda-scripts-lp-stderr.log
  - cat $PWD/logs/veda-scripts-main-stderr.log
  - cat $PWD/logs/veda-server-stderr.log
  - cat $PWD/logs/veda-gowebserver-stderr.log 
   
after_success: 
  - ./update-gh-pages.sh
