sudo: required
dist: trusty

addons:
  sauce_connect:
    username: semanticmachines
    access_key: 0fdd3d85-3d51-4fd5-89ed-10980baa57a5
    no_ssl_bump_domains: localhost

env:
  global:
    - secure: PYwCZBpLe87Qg2RXibiGk9LrNrkFMlGuFnf/mp+f5kc4bFoVMo7Pl+Rdl4S1H33kLYK6d3pFggddwWxO7HGH9IyHzQ6Gfu3u9gR9rJXovQYfEp8muDCJDXvLEUoMxRgnRPa202p+BUnrNMwebxYHmwgef0s1dYQpRsewmPWHevk=
    - secure: s1BV5JjhQIIdasowuMW2OqH5LjvN3tnU+sEGdz4HxWpHufgFUeNBVzu13S85qSxdch55lCyB4ft58PAX3q0wHFPYvBEwkvMlSFny7LeiytW9HZ/fkCG+Dwh6H6OEK1jKQriXZrYLQm4m6gnnAQYsUpDhxP12YejyyBbfaVW73Og=

# Load all dependencies
# Compile vibe-d before main project to prevent OutOfMemory issue
before_install:
  - ./control-install.sh&>install.log    
#  - cat install.log
  - dub -v fetch vibe-d --version=0.7.30
  - npm install selenium-webdriver@2.47.0
  - npm install -g grunt-cli
  - npm install grunt-contrib-qunit --save-dev
  - npm install grunt --save-dev
  - npm install coveralls --save-dev
  - npm install grunt-coveralls --save-dev

# Build
install:
  - ./build.sh

# Run service as daemon and GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
#  - start-stop-daemon --start --verbose --chdir $PWD --make-pidfile --pidfile $PWD/veda-pid --background --startas /bin/bash -- -c "exec ./veda >> $PWD/veda_s.log 2>&1"
  - ./control-start.sh
  - sleep 90  # give Web server some time to bind to sockets, load startup data, etc
  - ls  $PWD   
  - ls  $PWD/logs   
#  - cat $PWD/logs/veda-fanout-email-stderr.log
#  - cat $PWD/logs/veda-fanout-sql-stderr.log
#  - cat $PWD/logs/veda-ft-indexer-stderr.log
#  - cat $PWD/logs/veda-ltr-scripts-stderr.log
#  - cat $PWD/logs/veda-scripts-lp-stderr.log
#  - cat $PWD/logs/veda-scripts-main-stderr.log
#  - cat $PWD/logs/veda-mstorage-stderr.log
#  - cat $PWD/logs/veda-ttlreader-stderr.log
#  - cat $PWD/logs/veda-webserver-stderr.log 
#  - cat $PWD/veda_s.log
  - cat $PWD/logs/veda-core-mstorage_*.log          
  - setsid ./qa/uptime-to-log.sh&
  - cat ./uptime.log

# Run API & integration test
script:
  - grunt test --stack --verbose
#  - grunt coveralls
#  - node ./qa/testAPI.js
#  - node ./qa/testSendGet.js
#  - node ./qa/testLogin.js
#  - node ./qa/testDrafts.js
#  - node ./qa/testLanguage.js
#  - node ./qa/testDeleteAndRecovery.js
#  - node ./qa/testRights.js
#  - node ./qa/testComment.js
#  - node ./qa/testVersionedDocument.js
#  - node ./qa/testJournal.js
#  - node ./qa/testAttachment.js
#  - node ./qa/testPager.js
#  - node ./qa/testSearchRangeOfDates.js
#  - node ./qa/testAttributiveSearchPerson.js
#  - node ./qa/testCreatingNetInterface.js
#  - node ./qa/testInbox.js
#  - node ./qa/testRepeatComplexRoute.js
#  - node ./qa/testNetComplexRoute.js
#  - node ./qa/testSimpleNet.js
#  - node ./qa/testSimpleNet2.js
#  - node ./qa/testSimpleNet3.js
#  - node ./qa/testSimpleWorkflow.js
  - node ./qa/testDelegationDocument.js

# Stop deamon and show log
after_script:
  - start-stop-daemon -Kp $PWD/veda-pid $PWD/veda
  - cat ./uptime.log
  - grunt coveralls
  - date    
  - cat $PWD/veda_s.log
#  - cat logs/veda-core-_*.log 
#  - cat logs/veda-core-fanout_*.log
#  - cat logs/veda-core-fulltext_indexer_*.log
#  - cat logs/veda-core-ltr_scripts_*.log
#  - cat veda-core-scripts_*.log
#  - cat logs/veda-core-mstorage_*.log
#  - cat logs/veda-core-ttl_reader_*.log
#  - cat logs/veda-core-webserver_*.log 
